name: Container Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  container-release:
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
    uses: berntpopp/genefoundry-router/.github/workflows/_container-release.yml@58d011d9c72efe90337244342fdec703f2b5b4b9 # genefoundry-router container-release standard v1
