name: Container Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  container-release:
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
    uses: berntpopp/genefoundry-router/.github/workflows/_container-release.yml@25ac0f7ace0afc235e630694d25d0ba4236712e4 # genefoundry-router container-release standard v1
